# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bbs"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/cfhttp"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/clock"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/consuladapter"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/debugserver"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/diego-logging-client"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/durationjson"

[[constraint]]
  name = "code.cloudfoundry.org/go-loggregator"
  version = "6.0.0"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/inigo"

[[constraint]]
  name = "code.cloudfoundry.org/lager"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/locket"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/shlex"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.6"

[[constraint]]
  name = "github.com/kr/pty"
  version = "1.1.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/pborman/getopt"

[[constraint]]
  name = "github.com/pkg/sftp"
  revision = "e84cc8c755ca39b7b64f510fe1fffc1b51f210a5"

[[constraint]]
  branch = "master"
  name = "github.com/tedsuo/ifrit"

[[constraint]]
  name = "github.com/tedsuo/rata"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[prune]
  go-tests = true
  unused-packages = true
